apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mydb
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin123
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: myvolume
          mountPath: /var/lib/mysql
  volumes:
    - name: myvolume
      emptyDir: {}


