apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    app: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/thetak561/Ingress/volumes

