apiVersion: v1
kind: Service
metadata:
  name: hesdless-service
  labels:
    app: test
spec:
  ClusterIP: None
  ports:
    - targetPort: 3306
      port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ststeful-dep
  labels:
    app: test
spec:
  replicas: 3
  serviceName: hesdless-service
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: admin123
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
      volummCliamTemplate:
        - metadata:
            name: mysql-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
...

