apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    app: volume
spec:
  containers:
    - name: my-redis
      image: redis
      volumeMounts:
        - name: myvolume
          mountPath: /data/redis
  volumes:
    - name: myvolume
      emptyDir: {}

