apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      containers:
        - name: my-task
          image: tawfeeq421/company
          ports:
            - containerPort: 3000

